---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - host_vars/couch-instance-vars.yaml
  gather_facts: true

  roles:
    - role: common
    - role: volumes
    - role: security-groups
    - role: instances

- hosts: inst-couchDB
  vars_files:
    - host_vars/couch-instance-vars.yaml
    - host_vars/couchDB_vars.yaml
  gather_facts: true

  #handlers:
  #  - include: frontend-handlers/handler.yaml

  roles:
    - role: server-common
    - role: couch-install


- hosts: inst-couchDB2
  vars_files:
    - host_vars/couch-instance-vars.yaml
    - host_vars/couchDB_vars.yaml
  gather_facts: true

  #handlers:
  #  - include: frontend-handlers/handler.yaml

  roles:
    - role: server-common
    - role: couch-install
