---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - host_vars/frontend-vars.yaml
  gather_facts: true

  roles:
    - role: common
    - role: volumes
    - role: security-groups
    - role: instances



- hosts: frontend-instance
  vars_files:
    - host_vars/frontend-vars.yaml
  gather_facts: true

  roles:
    - role: server-common
    - role: frontend-docker-install
