---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - host_vars/group-3-frontend.yaml
  gather_facts: true

  roles:
    - role: common
    - role: volumes
    - role: security-groups
    - role: instances



- hosts: inst-couchDB
  vars_files:
    - host_vars/group-3-frontend.yaml
    - host_vars/couchDB_vars.yaml
  gather_facts: true

  #handlers:
  #  - include: frontend-handlers/handler.yaml

  roles:
    - role: frontend-couch
