---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/group-2-instance.yaml
  gather_facts: true

  roles:
    - role: instance-common
    - role: instance-volumes
    - role: instance-security-groups
    - role: instance-instances
    - role: docker-install