---
# create an instance on MRC
- name: create an instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ item.instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volume }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instance

- name: setting the os_instance variable
  set_fact:
    os_instances_ips: '{{ os_instance.results }}'

- debug:
    msg: "Instances {{ item.openstack.name }} created. IP address {{ item.openstack.public_v4 }}"
  loop: '{{os_instances_ips}}'
  when: item.openstack is defined

- name: wait for conn
  wait_for: 
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{os_instances_ips}}'
  when: item.openstack is defined

- name: changing security for key
  file:
    path: new_key_sm.pem
    state: file
    mode: '700'

  # add hosts to ansible in-memory inventory
- name: add host
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: '{{ item.openstack.name }}'
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_user: ubuntu
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /Users/trinadey/.ssh/new_key_sm.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  loop: '{{os_instances_ips}}'
  when: item.openstack is defined


