- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc_playbook.yaml
  gather_facts: true

  roles:
    -role: openStack_common
    -role: openStack_volume
    -role: openStack_security_groups
    -role: openstack_instance
    -role: openstack_volume_snapshot
     