- name: Add Erlang repository key
  become: yes
  apt_key: 
    url: http://packages.erlang-solutions.com/debian/erlang_solutions.asc 
    state: present
  

- name: Add Erlang repository
  become: yes
  apt_repository:
    repo: "deb http://packages.erlang-solutions.com/debian focal main" 
    mode: '644'
    update_cache: yes
    state: present
  
  
- name: Install erlang-nox
  become: yes
  apt: 
    name: erlang-nox 
    state: present
  
  
- name: Install erlang-dev
  become: yes
  apt: 
    name: erlang-dev 
    state: present 
   
  
- name: Install libmozjs185-1.0
  become: yes
  apt: 
    name: libmozjs185-1.0 
    state: present  

- name: Install libmozjs185-dev
  become: yes
  apt: 
    name: libmozjs185-dev 
    state: present  
  
  
- name: Install libcurl4-openssl-dev
  become: yes
  apt: 
    name: libcurl4-openssl-dev 
    state: present  
  
   
- name: Install libicu-dev
  become: yes
  apt: 
    name: libicu-dev 
    state: present  
