---
# create an instance on MRC
- name: create an instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ item.instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volume }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instance

- debug:
    msg: "Intances {{ item.openstack.name }} created. IP address {{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: wait for conn
  wait_for: 
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instances.results }}'
  when: item.openstack is defined


  # add hosts to ansible in-memory inventory
  - name: add host
    add_host:
      name: '{{ item.openstack.public_v4 }} '
      groups: COMP90024
    loop: '{{ os_instances.results }}'
    when: item.openstack is defined