---
# - name: Gather facs of remote host
#  setup: 
#    gather_subnet: all

- name: Install pip
  become: yes
  apt:
    name: ['python3-pip', 'apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  
- name: Update pip
  pip:
    name: ['pip']
    state: latest

- name: Install openstacksdk
  pip:
    name: ['openstacksdk==0.52']
    state: latest
# pip install openstacksdk

- name: Install tweepy
  pip:
    name: ['tweepy']
    state: latest


- name: Install couchDb
  pip:
    name: ['couchdb']
    state: latest
# pip install couchdb

